---
- hosts: ocp4-helpernode
  tasks:
  - include_vars:
      file: vars.yaml

  - name: install jq
    dnf:
      name: jq
      state: latest
      update_cache: yes

  - name: approve CSRs
    shell: |
      export KUBECONFIG={{ installdir }}/auth/kubeconfig
      CSR=some
      while true; do 
        if [[ $CSR =~ .*error.* ]] ; then
          echo $CSR
          exit 0
        fi
        CSR="$(oc get csr -ojson | jq -r '.items[] | select(.status == {} ) | .metadata.name' | xargs oc adm certificate approve 2>&1)"
        echo $CSR
        sleep 60
      done
    args:
      executable: /bin/bash
