---
- hosts: ocp4-helpernode
  tasks:
  - include_vars:
      file: vars.yaml

  - name: Fetch kubeadmin password
    fetch:
      src: "{{ installdir }}/auth/kubeadmin-password"
      dest: ../kubeadmin-password
      flat: yes
      mode: 0666
      
  - name: Fetch kubeconfig file
    fetch:
      src: "{{ installdir }}/auth/kubeconfig"
      dest: ../kubeconfig
      flat: yes
      mode: 0666
